### ISSUE TITLE
Stale data: Valid email addresses changed in the last few weeks are missing

### ISSUE THREAD

**Issue by MasterKale** [netlify/million-devs#32]
For some reason, the website is unable to reveal my number:

<img width="611" alt="Screen Shot 2020-08-03 at 9 44 49 AM" src="https://user-images.githubusercontent.com/5166470/89206494-3923fc80-d56e-11ea-9822-5beff83234d6.png">

> Welcome to the Netlify community! It doesn't look like you were in our first million users, but we're glad you're here!

This is despite my being a Netlify user since April 2018:

<img width="703" alt="Screen Shot 2020-08-03 at 9 46 01 AM" src="https://user-images.githubusercontent.com/5166470/89206514-40e3a100-d56e-11ea-8b96-b1853ab9622f.png">

The website and its timeline celebrate Netlify just now onboarding a million users, so shouldn't I have a number?

**Comment by zachleat** [comment]
Interesting. I do see your userid in the data set but not the same email. Did you change your email recently?

**Comment by zachleat** [comment]
You’re #197,999 by the way

**Comment by dannylee8** [comment]
Similar issue, I recently updated my email and it doesn't show up. If I change it back to my to old email address I show up #177ksomething.

**Comment by zachleat** [comment]
Ah, yes—correct, sorry about that. The data source is a static copy from a few weeks back.

**Comment by MasterKale** [comment]
@zachleat According to my password locker I last updated my Netlify login on 7/22, and now that I think about it it was probably to change to a different email address. Perhaps that explains what's going on?

**Comment by dannylee8** [comment]
@zachleat great site - much fun seeing who in my network was earliest adopter!
